"""
Connection Agent — Sends personalized LinkedIn connection requests.

Handles:
  - Navigate to a profile URL
  - Click "Connect" button (handles various LinkedIn UI states)
  - Add a personalized note (generated by LLM or from template)
  - Confirm the request was sent
  - Handle "Already connected", "Pending", "Follow" states
"""

from __future__ import annotations

import asyncio
import re
from typing import Any, Dict, List, Optional

from loguru import logger

from .base_agent import BaseAgent


# ── Note Templates ────────────────────────────────────────────────────────────

DEFAULT_NOTE_TEMPLATES = [
    "Hi {name}, I came across your profile and was impressed by your work in {field}. "
    "I'd love to connect and learn from your experience!",

    "Hi {name}, your background in {field} caught my attention. "
    "I'm also working in this space and would love to connect!",

    "Hello {name}, I noticed your work at {company} and would love to add you to my network. "
    "Looking forward to connecting!",
]


class ConnectionAgent(BaseAgent):
    """
    Sends a personalized connection request to a LinkedIn profile.

    Per-profile usage:
        agent = ConnectionAgent(...)
        result = await agent.run(pc, context={
            "profile": {"name": "John Doe", "url": "...", "title": "...", "company": "..."},
            "note": "Hi John, ...",  # optional custom note
        })
    """

    def __init__(self, **kwargs):
        super().__init__(name="ConnectionAgent", max_steps=10, **kwargs)
        self._profile: Dict[str, Any] = {}
        self._note: str = ""
        self._connection_status: str = "unknown"

    @property
    def goal(self) -> str:
        name = self._profile.get("name", "unknown")
        return f"Send connection request to {name}"

    async def run(self, page_controller, context: Optional[Dict] = None) -> Dict[str, Any]:
        """Override run to inject profile context."""
        ctx = context or {}
        self._profile = ctx.get("profile", {})
        self._note = ctx.get("note", "")
        self._connection_status = "unknown"

        # Generate note if not provided
        if not self._note and self._profile:
            self._note = self._generate_note(self._profile)

        return await super().run(page_controller, context)

    async def execute_step(
        self,
        page_controller,
        screenshot_b64: str,
        experiences: List[Dict],
        step: int,
    ) -> Dict[str, Any]:
        """Execute one connection step."""

        url = page_controller.url
        profile_url = self._profile.get("url", "")

        # Step 1: Navigate to profile
        if step == 1:
            return await self._navigate_to_profile(page_controller, profile_url)

        # Step 2: Find and click Connect button
        if step == 2:
            return await self._click_connect(page_controller)

        # Step 3: Add note and send
        if step == 3:
            return await self._add_note_and_send(page_controller)

        # Step 4: Confirm sent
        if step >= 4:
            return await self._confirm_sent(page_controller)

        return {"action": "wait", "success": True, "done": False}

    # ── Connection Steps ──────────────────────────────────────────────────────

    async def _navigate_to_profile(self, pc, profile_url: str) -> Dict[str, Any]:
        """Navigate to the target profile."""
        if not profile_url:
            return {
                "action": "navigate_profile",
                "success": False,
                "done": True,
                "abort": True,
                "error": "No profile URL provided",
            }

        self.log_step(f"Navigating to profile: {profile_url}")
        result = await pc.navigate(profile_url, timeout=20000)
        await pc.wait_for_load(timeout=10000)
        await asyncio.sleep(2)

        return {
            "action": "navigate_profile",
            "success": result.get("success", False),
            "done": False,
        }

    async def _click_connect(self, pc) -> Dict[str, Any]:
        """Find and click the Connect button on the profile."""
        self.log_step("Looking for Connect button")

        # Check current connection status first
        status = await self._get_connection_status(pc)
        self._connection_status = status

        if status == "connected":
            self.log_step("Already connected with this person")
            return {
                "action": "click_connect",
                "success": True,
                "done": True,
                "result": {"status": "already_connected", "profile": self._profile},
            }

        if status == "pending":
            self.log_step("Connection request already pending")
            return {
                "action": "click_connect",
                "success": True,
                "done": True,
                "result": {"status": "already_pending", "profile": self._profile},
            }

        # Try to find Connect button (various LinkedIn UI patterns)
        connect_selectors = [
            # Direct connect button on profile
            "button.pvs-profile-actions__action[aria-label*='Connect']",
            "button[aria-label*='Connect with']",
            "button[aria-label='Connect']",
            # Connect in the action buttons area
            ".pv-s-profile-actions button:has-text('Connect')",
            # More options → Connect
            "button.artdeco-button--secondary[aria-label*='Connect']",
        ]

        connect_clicked = False
        for selector in connect_selectors:
            exists = await pc.element_exists(selector)
            if exists:
                result = await pc.click_selector(selector, timeout=5000)
                if result.get("success"):
                    connect_clicked = True
                    break

        if not connect_clicked:
            # Try "More" button → Connect
            connect_clicked = await self._try_more_menu_connect(pc)

        if not connect_clicked:
            self.log_step("Connect button not found", "warning")
            return {
                "action": "click_connect",
                "success": False,
                "done": True,
                "error": "Connect button not found — profile may be private or already connected",
                "result": {"status": "button_not_found", "profile": self._profile},
            }

        await asyncio.sleep(1)
        return {
            "action": "click_connect",
            "success": True,
            "done": False,
        }

    async def _add_note_and_send(self, pc) -> Dict[str, Any]:
        """Add a personalized note and send the connection request."""
        self.log_step("Adding note to connection request")

        # Check if "Add a note" dialog appeared
        dialog_exists = await pc.element_exists(
            ".send-invite__actions, .artdeco-modal, [data-test-modal]"
        )

        if not dialog_exists:
            # Dialog might not have appeared — check if request was auto-sent
            await asyncio.sleep(1)
            return await self._confirm_sent(pc)

        # Click "Add a note" button if present
        add_note_btn = await pc.element_exists(
            "button[aria-label='Add a note'], button:has-text('Add a note')"
        )
        if add_note_btn:
            await pc.click_selector(
                "button[aria-label='Add a note'], button:has-text('Add a note')"
            )
            await asyncio.sleep(0.5)

        # Fill in the note
        note_textarea = await pc.element_exists(
            "textarea#custom-message, textarea[name='message'], "
            ".send-invite__custom-message textarea"
        )

        if note_textarea and self._note:
            await pc.fill_input(
                "textarea#custom-message, textarea[name='message'], "
                ".send-invite__custom-message textarea",
                self._note[:300],  # LinkedIn limit: 300 chars
                human_like=True,
            )
            await asyncio.sleep(0.5)

        # Click Send / Done button
        send_selectors = [
            "button[aria-label='Send now']",
            "button[aria-label='Send invitation']",
            "button:has-text('Send')",
            "button:has-text('Done')",
            ".artdeco-modal__actionbar button.artdeco-button--primary",
        ]

        sent = False
        for selector in send_selectors:
            exists = await pc.element_exists(selector)
            if exists:
                result = await pc.click_selector(selector, timeout=5000)
                if result.get("success"):
                    sent = True
                    break

        if not sent:
            return {
                "action": "add_note_send",
                "success": False,
                "done": True,
                "error": "Could not find Send button",
            }

        await asyncio.sleep(1)
        return {
            "action": "add_note_send",
            "success": True,
            "done": False,
        }

    async def _confirm_sent(self, pc) -> Dict[str, Any]:
        """Confirm the connection request was sent."""
        self.log_step("Confirming connection request sent")

        # Check for success indicators
        success_indicators = [
            "button[aria-label*='Pending']",
            "button[aria-label='Withdraw invitation']",
            ".artdeco-inline-feedback--success",
            "[data-test-pending-connection]",
        ]

        for selector in success_indicators:
            if await pc.element_exists(selector):
                self.log_step(f"Connection request confirmed sent to {self._profile.get('name')}", "info")
                return {
                    "action": "confirm_sent",
                    "success": True,
                    "done": True,
                    "result": {
                        "status": "request_sent",
                        "profile": self._profile,
                        "note_used": self._note[:50] if self._note else "",
                    },
                }

        # Check if "Pending" text appears anywhere
        page_text = await pc.get_text(".pv-s-profile-actions, .pvs-profile-actions")
        if "pending" in page_text.lower() or "withdraw" in page_text.lower():
            return {
                "action": "confirm_sent",
                "success": True,
                "done": True,
                "result": {
                    "status": "request_sent",
                    "profile": self._profile,
                },
            }

        # Assume sent if no error visible
        return {
            "action": "confirm_sent",
            "success": True,
            "done": True,
            "result": {
                "status": "likely_sent",
                "profile": self._profile,
            },
        }

    # ── Helpers ───────────────────────────────────────────────────────────────

    async def _get_connection_status(self, pc) -> str:
        """Determine current connection status with this profile."""
        status_checks = {
            "connected": [
                "button[aria-label*='Message']",
                ".pv-s-profile-actions button[aria-label='Message']",
            ],
            "pending": [
                "button[aria-label*='Pending']",
                "button[aria-label='Withdraw invitation']",
            ],
        }

        for status, selectors in status_checks.items():
            for selector in selectors:
                if await pc.element_exists(selector):
                    return status

        return "not_connected"

    async def _try_more_menu_connect(self, pc) -> bool:
        """Try to find Connect via the 'More' dropdown menu."""
        more_btn = await pc.element_exists(
            "button[aria-label='More actions'], button:has-text('More')"
        )
        if not more_btn:
            return False

        await pc.click_selector("button[aria-label='More actions'], button:has-text('More')")
        await asyncio.sleep(0.5)

        connect_in_menu = await pc.element_exists(
            ".artdeco-dropdown__content li button:has-text('Connect')"
        )
        if connect_in_menu:
            result = await pc.click_selector(
                ".artdeco-dropdown__content li button:has-text('Connect')"
            )
            return result.get("success", False)

        return False

    def _generate_note(self, profile: Dict[str, Any]) -> str:
        """Generate a personalized connection note from profile data."""
        import random
        template = random.choice(DEFAULT_NOTE_TEMPLATES)

        name = profile.get("name", "").split()[0] if profile.get("name") else "there"
        title = profile.get("title", "")
        company = profile.get("company", "your company")

        # Extract field from title
        field = "your field"
        if title:
            # Take first 2-3 words of title as field
            words = title.split()[:3]
            field = " ".join(words).lower()

        note = template.format(
            name=name,
            field=field,
            company=company,
        )
        return note[:300]  # LinkedIn 300 char limit
